SIDEBAR_CONTROLS = [
    {
        "id": "ip_velocity_submissions",
        "label": "IP submissions in 5 minutes",
        "kind": "slider",
        "min": 0,
        "max": 12,
        "default": 0,
        "step": 1,
        "help": "Layer 1 rejects when an IP has more than 3 submissions in 5 minutes.",
    },
    {
        "id": "form_completion_seconds",
        "label": "Form completion seconds",
        "kind": "slider",
        "min": 0.0,
        "max": 60.0,
        "default": 10.0,
        "step": 0.5,
        "help": "Layer 1 rejects submissions completed in under 3 seconds.",
    },
    {
        "id": "duplicate_count",
        "label": "Exact duplicates within 1 hour",
        "kind": "slider",
        "min": 0,
        "max": 10,
        "default": 0,
        "step": 1,
        "help": "Duplicates represent identical comp/location payloads from the recent window.",
    },
    {
        "id": "sequential_padding_detected",
        "label": "Sequential salary padding",
        "kind": "toggle",
        "default": False,
        "help": "Flags bot-like sequences such as 100k, 101k, 102k from the same actor.",
    },
    {
        "id": "distinct_session_locations",
        "label": "Distinct locations per session",
        "kind": "slider",
        "min": 1,
        "max": 8,
        "default": 1,
        "step": 1,
        "help": "Layer 1 rejects when a session rotates through more than 3 locations.",
    },
    {
        "id": "distinct_session_titles",
        "label": "Distinct titles per session",
        "kind": "slider",
        "min": 1,
        "max": 8,
        "default": 1,
        "step": 1,
        "help": "Layer 1 rejects when a session rotates through more than 3 titles.",
    },
    {
        "id": "honeypot_filled",
        "label": "Honeypot field filled",
        "kind": "toggle",
        "default": False,
        "help": "Hidden CSS form fields should stay empty for human submissions.",
    },
    {
        "id": "proof_uploaded",
        "label": "Offer letter / W-2 / paystub uploaded",
        "kind": "toggle",
        "default": False,
        "help": "Adds +0.30 to the user trust multiplier before capping.",
    },
    {
        "id": "domain_match",
        "label": "Work email domain matches company",
        "kind": "toggle",
        "default": False,
        "help": "Adds +0.15 to the user trust multiplier.",
    },
    {
        "id": "social_sso",
        "label": "LinkedIn or GitHub SSO",
        "kind": "toggle",
        "default": False,
        "help": "Adds +0.05 to the user trust multiplier.",
    },
    {
        "id": "approved_submission_count",
        "label": "Previously approved submissions",
        "kind": "slider",
        "min": 0,
        "max": 20,
        "default": 0,
        "step": 1,
        "help": "Adds +0.10 once the account has 3 or more approved submissions.",
    },
    {
        "id": "account_age_days",
        "label": "Account age in days",
        "kind": "slider",
        "min": 0,
        "max": 1500,
        "default": 0,
        "step": 10,
        "help": "Adds +0.05 when the account is older than one year.",
    },
    {
        "id": "reject_ratio",
        "label": "Historical reject ratio",
        "kind": "slider",
        "min": 0.0,
        "max": 1.0,
        "default": 0.0,
        "step": 0.01,
        "help": "Subtracts -0.40 when more than 30 percent of prior submissions were rejected.",
    },
    {
        "id": "vpn_ip_risk",
        "label": "VPN / data-center IP risk",
        "kind": "toggle",
        "default": False,
        "help": "Subtracts -0.20 from the user trust multiplier.",
    },
]


ADVANCED_CONTROLS = [
    {
        "id": "rolling_window_days",
        "label": "Rolling window days",
        "kind": "slider",
        "min": 7,
        "max": 365,
        "default": 90,
        "step": 1,
        "help": "Layer 2 uses this trailing window for IQR statistics.",
    },
    {
        "id": "iqr_multiplier",
        "label": "IQR multiplier",
        "kind": "slider",
        "min": 0.5,
        "max": 3.0,
        "default": 1.618,
        "step": 0.001,
        "help": "Golden-ratio default for statistical acceptance bounds.",
    },
    {
        "id": "synthetic_rows",
        "label": "Synthetic benchmark target rows",
        "kind": "slider",
        "min": 0,
        "max": 1000,
        "default": 250,
        "step": 10,
        "help": "Expanded in memory only; original benchmark files are not changed.",
    },
    {
        "id": "ml_contamination",
        "label": "ML contamination",
        "kind": "slider",
        "min": 0.01,
        "max": 0.30,
        "default": 0.08,
        "step": 0.01,
        "help": "Expected anomaly fraction for Isolation Forest.",
    },
    {
        "id": "random_seed",
        "label": "Random seed",
        "kind": "number",
        "min": 0,
        "max": 99999,
        "default": 42,
        "step": 1,
        "help": "Controls synthetic data generation and Isolation Forest repeatability.",
    },
    {
        "id": "strict_currency_feasibility",
        "label": "Strict currency feasibility",
        "kind": "toggle",
        "default": False,
        "help": "Rejects values outside broad local-currency bounds.",
    },
    {
        "id": "min_ml_rows",
        "label": "Minimum rows for ML",
        "kind": "slider",
        "min": 10,
        "max": 200,
        "default": 40,
        "step": 5,
        "help": "Layer 3 waits until benchmark data has enough PASS rows.",
    },
    {
        "id": "require_shap",
        "label": "Require real SHAP explanations",
        "kind": "toggle",
        "default": True,
        "help": "If SHAP cannot run, Layer 3 is marked unavailable instead of faking reasons.",
    },
]
